# -*- coding: utf-8 -*-
"""crawling1.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13F5g5bM0qJ2FLf3ojFvfU0q-9VPsSAC6
"""

from selenium import webdriver
from time import sleep
import pandas as pd
import csv

driver = webdriver.Chrome(executable_path = r'C:\Users\변정민\Desktop\chromedriver.exe')
comments_list = []
likes_list = []
names_list = []

driver.get('https://search.daum.net/search?w=news&q=%EC%A4%91%EA%B5%AD&DA=PGD&spacing=0&p=1')
count = 1
page_num = 0

while len(comments_list) <= 2000 and len(likes_list) <= 4000:
    try:
        if count == 11:
            if page_num == 5:
                count = 1
                page = driver.find_element_by_class_name('ico_comm1.btn_page.btn_next')
                try:
                    while page != '':
                        page.click()
                except:
                    pass
            else:
                count = 1
                page_num += 1
                page = driver.find_element_by_xpath(f'// *[ @ id = "newsColl"] / div[4] / span / span[2] / a[{page_num}]')
                page.click()
            
            
        link = driver.find_element_by_xpath(f'//*[@id="clusterResultUL"]/li[{count}]/div[2]/div/span[1]/a')
        link.click()
        driver.switch_to.window(driver.window_handles[-1])
        sleep(3)
        
        #댓글 더보기버튼 없을 때까지 클릭
        try:
            while driver.find_element_by_xpath('//*[@id="alex-area"]/div/div/div/div[3]/div[3]/button').text !='':
                driver.find_element_by_xpath('//*[@id="alex-area"]/div/div/div/div[3]/div[3]/button').click()
                sleep(3)
        except:
            pass
        sleep(2)
        
        comment = driver.find_elements_by_class_name('desc_txt.font_size_17')
        comment = [c.text for c in comment]
        comments_list.extend(comment)
        
        like = driver.find_elements_by_class_name('num_txt')
        like = [l.text for l in like]
        likes_list.extend(like)
        
        name = driver.find_elements_by_class_name('link_nick')
        name = [n.text for n in name]
        names_list.extend(name)
        
        driver.close()
        driver.switch_to.window(driver.window_handles[-1])
        count += 1
        print(name, comment, like)
    except:
        count += 1
    sleep(3)

nms = pd.DataFrame(names_list)
nms.head()
nms.to_csv('nms_UTF8.csv', encoding = 'UTF-8-sig')

cmts = pd.DataFrame(comments_list)
cmts.head()
cmts.to_csv('cmts_UTF8.csv', encoding = 'UTF-8-sig')

lks = pd.DataFrame(likes_list)
lks.head()
lks.to_csv('lks_UTF8.csv', encoding = 'UTF-8')